server:
  port: 8080

spring:
  application:
    name: fullstack-app
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1111}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.pearldata: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: ${JWT_SECRET:mySecretKeyForPearlDataApplication2024}
  expiration: ${JWT_EXPIRATION:86400000}

# Twilio SMS & WhatsApp Configuration
twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:your_twilio_account_sid_here}
  auth:
    token: ${TWILIO_AUTH_TOKEN:your_twilio_auth_token_here}
  phone:
    number: ${TWILIO_PHONE_NUMBER:+15074323599}
  whatsapp:
    enabled: ${TWILIO_WHATSAPP_ENABLED:true}
    sandbox:
      from: ${TWILIO_WHATSAPP_FROM:whatsapp:+14155238886}
      to-prefix: ${TWILIO_WHATSAPP_TO_PREFIX:whatsapp:+91}
