server:
  port: 8080

spring:
  application:
    name: fullstack-app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.pearldata: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: mySecretKeyForPearlDataApplication2024
  expiration: 86400000
