server:
  port: 8080

spring:
  application:
    name: fullstack-app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.pearldata: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: mySecretKeyForPearlDataApplication2024
  expiration: 86400000

# Twilio SMS & WhatsApp Configuration
twilio:
  account:
    sid: your_twilio_account_sid_here
  auth:
    token: your_twilio_auth_token_here
  phone:
    number: +15074323599  # Twilio trial number (replace with your Twilio number)
  whatsapp:
    enabled: true
    sandbox:
      from: whatsapp:+14155238886  # Twilio WhatsApp Sandbox number
      to-prefix: whatsapp:+91  # Prefix for Indian numbers
